### ISSUE TITLE
Criar protótipo de baixa fidelidade

### ISSUE THREAD

**Issue by lievertom** [Feudo-Laranja-ave-do-paraiso-DS-2021-2/wiki#14]
## Descrição

- Com o objetivo de pensar na interface inicial do projeto, criar protótipos de baixa fidelidade.

Criar protótipos de baixa fidelidade no modelo de [wireframe](https://aelaschool.com/designdeinteracao/wireframe-o-que-e-como-desenhar/#:~:text=Wireframes%20s%C3%A3o%20esbo%C3%A7os%20simples%20de,digitais%2C%20como%20sites%20e%20aplicativos.&text=Os%20wireframes%2C%20possuem%20dois%20objetivos,quer%20e%20ao%20projeto%20criado) .

## Critérios de Aceitação [?](http://www.metodoagil.com/historias-de-usuario/)

- As imagens dos protótipos devem ser adicionadas como comentário nessa issue.

## Observações 

- pode ser desenvolvido em uma folha de papel ou usando uma aplicação online

**Comment by PedroSampaioDias** [comment]
![Frame_protótipo_de_baixa_fidelidade](https://user-images.githubusercontent.com/90795603/154727718-43381417-3dd1-44d6-8a7f-20f316272c97.png)

![Frame_protótipo_de_baixa_fidelidade-1](https://user-images.githubusercontent.com/90795603/154727928-5404e48f-de22-40cf-b057-d2146348f01b.png)

**Comment by Leanddro13** [comment]
![wireframe](https://user-images.githubusercontent.com/86811628/154740590-965547b7-17b6-44f3-978a-efcfd1cdaeb9.png)

**Comment by Victor-oss** [comment]
![Pg1](https://user-images.githubusercontent.com/55855365/154748648-5d6a3d92-063c-49eb-a9e2-7147f15a19f6.png)
![Pg2](https://user-images.githubusercontent.com/55855365/154748651-8135ad05-eaa5-4660-a807-07262153a7a0.png)
![Pg3](https://user-images.githubusercontent.com/55855365/154748653-a0e5323b-f448-4d1b-9160-c13a7406e9fb.png)
![Pg4](https://user-images.githubusercontent.com/55855365/154748655-64c6da4b-c4e1-4d57-8c82-4a0304282553.png)
![Pg5](https://user-images.githubusercontent.com/55855365/154748657-318ddc2b-28a4-4ee0-bc09-74619317934c.png)
![Pg6](https://user-images.githubusercontent.com/55855365/154748659-2e59cd8d-99b2-41a2-bc5c-e0df1b908c64.png)
![Pg7](https://user-images.githubusercontent.com/55855365/154748660-ae53336d-f20b-4793-b4d0-a7ed4b806794.png)
![Pg8](https://user-images.githubusercontent.com/55855365/154748661-d0196759-8b37-4e3b-b9b5-150fa45452a0.png)

**Comment by PedroFMuniz** [comment]
[Copilot.pdf](https://github.com/Feudo-Laranja-ave-do-paraiso-DS-2021-2/wiki/files/8102856/Copilot.pdf)

**Comment by marcusmartinsxx** [comment]
[prototipo_BF.pdf](https://github.com/Feudo-Laranja-ave-do-paraiso-DS-2021-2/wiki/files/8103344/prototipo_BF.pdf)

**Comment by marcusmartinss** [comment]
[prototipoBF.pdf](https://github.com/Feudo-Laranja-ave-do-paraiso-DS-2021-2/wiki/files/8103347/prototipoBF.pdf)
